export enum ProductOfferActions {
  ACCEPT_PRODUCT_OFFER = 'productOffer/ACCEPT_PRODUCT_OFFER',
  CREATE_PRODUCT_OFFER = 'productOffer/CREATE_PRODUCT_OFFER',
  REJECT_PRODUCT_OFFER = 'productOffer/REJECT_PRODUCT_OFFER',
  SET_PRODUCT_OFFER_ERROR = 'productOffer/SET_PRODUCT_ERROR',
  SET_PRODUCT_OFFER_SUCCESS = 'productOffer/SET_PRODUCT_SUCCESS',
}
